/*
 * This source file was generated by the Gradle 'init' task
 */
package maptool;

public class App {
        public static void main(String[] args) {
        // Spawn our GUI.
        GUI gui = new GUI();
        gui.createUI();
        
        // Run our testing encode.
        jmp jmp = new jmp();
    }
}
